language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - pip install -r requirements.txt
script:
  - pip install -r dev-requirements.txt
  - flake8 setup.py drone tests
  - nosetests --with-coverage --cover-package drone -v